# Generated by Django 4.1.4 on 2022-12-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daftar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesanan', models.CharField(max_length=20)),
                ('jumlah', models.IntegerField(null=True)),
            ],
        ),
    ]
