# Generated by Django 4.1.4 on 2022-12-27 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cemilan', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Daftar',
            new_name='Cemilan',
        ),
    ]
